### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by hitesh-shukla** [drosendo/whmcs-custom-apis#1]
i have uploaded the file into api folder but getting
{
"result": "error",
"message": "Invalid Permissions: API action "getproductsactive" is not allowed"
}

**Comment by drosendo** [comment]
You must check that the user has permission to access API requests.

Sorry for late reply, didnt see the message.

**Comment by monovm** [comment]
hi 
i have tested and we have this error 
"message": "Invalid Permissions: API action \u0022getproductsactive\u0022 is not allowed"
regards

**Comment by ferdyzz4** [comment]
Great, It's still worked fine for me. Thanks @drosendo
