### ISSUE TITLE
"Invalid Permissions: API action \"getproductsgroups\" is not allowed"

### ISSUE THREAD

**Issue by CodingButter** [drosendo/whmcs-custom-apis#2]
Ive uploaded the files to the api directory and i'm presented this error when i set the action to GetProductsGroups
{"result":"error","message":"Invalid Permissions: API action \u0022getproductsgroups\u0022 is not allowed"}

**Comment by edgesite** [comment]
![image](https://user-images.githubusercontent.com/10336620/135920934-9209175a-571e-4aee-804d-5de195d9e8b9.png)

WHMCS 8 strictly limits API permissions, and API roles manager don't support custom APIs. You need to edit tblapi_roles table, add GetProductsGroups and GetProductsActive manually. Just merge follows to field permissions:
{"getproductsactive": 1, "getproductsgroups": 1}

**Comment by drosendo** [comment]
Hello,

I had already created a code to register this automatically sorry I didn't share it before but it's now available [here](https://github.com/drosendo/whmcs-custom-apis/blob/82fa2de58ecfe52cf61bf0a69402a441afc3cf1d/includes/api/getproductsgroups.php)

Cheers,
David
