### ISSUE TITLE
Role Management group

### ISSUE THREAD

**Issue by bilalkh4an** [drosendo/whmcs-custom-apis#4]
In role management group, the group and action created successfully but unfortunately after deleting the files we are unable to delete the created role group and action in WHMCS, may i please know how to delete the group and action from WHMCS admin portal

**Comment by drosendo** [comment]
You will have to probably go to the DB and remove it from there. I still havent review the option to delete.

**Comment by bilalkh4an** [comment]
May I please know the table name to do so ?

**Comment by drosendo** [comment]
I stopped working with WHMCS will be faster just to search the DB for the value.
