### ISSUE TITLE
addPromoCode

### ISSUE THREAD

**Issue by FTomasz** [drosendo/whmcs-custom-apis#5]
Hello there, I was wondering if it would be possible for you to create an API that allows me to create Promotion codes through an API, I would happily pay you to create this feature, and happily allow you to distribute it publicly.

Kind regards,

Freddie Tomaszewski

**Comment by drosendo** [comment]
Hello,

I have replied via email.

Cheers,

**Comment by FTomasz** [comment]
Hello, I don't believe I can see an email from you in my account can I confirm this was to fr****ski@gmail.com?

**Comment by drosendo** [comment]
Hi,

Yes it was the email on the message to reply to.

Cheers

**Comment by FTomasz** [comment]
perhaps I mispelled my email address then, would I be able to send you an email to check?

**Comment by drosendo** [comment]
Sure, contact me via www.rosendo.pt

**Comment by drosendo** [comment]
CHeck out: https://github.com/drosendo/whmcs-custom-apis/blob/master/includes/api/addpromocode.php

**Comment by andretunes** [comment]
Hello @drosendo,

I was checking it out, because got this in my dm. You're calling the API `AddPromo` and `UpdatePromo`, but neither isn't a legacy API from WHMCS, and neither did you upload it. Did you forget to upload it?

Cheers,
André

**Comment by drosendo** [comment]
damm.. forget to upload the rest :) do it tomorrow.

**Comment by andretunes** [comment]
No problem mate, just to help your community uploads.
